#!/bin/csh

foreach one ( *py )
    echo $one --------------------------------------------------------------------------------------------------------------
    diff /usr/local/lib/python2.4/site-packages/sqlobject/${one} $one
end

